name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - name: Build library
        run: npm run build

      - name: Create release archive
        run: |
          tar -czf react-split-flap-effect-${{ github.ref_name }}.tar.gz dist/ package.json README.md
          zip -r react-split-flap-effect-${{ github.ref_name }}.zip dist/ package.json README.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Installation

            Install directly from GitHub:
            ```bash
            npm install github:gilles-yvetot/react-split-flap-effect#${{ github.ref_name }}
            ```

            Or download the built assets from this release.

            ## Changes
            See [CHANGELOG.md](CHANGELOG.md) for details.
          draft: false
          prerelease: false

      - name: Upload Release Asset (tar.gz)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./react-split-flap-effect-${{ github.ref_name }}.tar.gz
          asset_name: react-split-flap-effect-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Asset (zip)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./react-split-flap-effect-${{ github.ref_name }}.zip
          asset_name: react-split-flap-effect-${{ github.ref_name }}.zip
          asset_content_type: application/zip
